version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/php:8.2-bullseye
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspaces/mm-pim
    working_dir: /workspaces/mm-pim
    command: sleep infinity

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pim_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
